{% set version = os.environ.get("MAXICONDA_SHORTCUTS_VERSION", "") %}

package:
  name: maxiconda-shortcuts
  version: {{ version }}

build:
  number: 0
  skip: True  # [not win]

test:
  commands:
    - if not exist %PREFIX%\\Menu\\maxiconda_shortcuts.json exit 1
    - if not exist %PREFIX%\\Menu\\spyder.ico exit 1
    - if not exist %PREFIX%\\Menu\\cmd.ico exit 1
    - if not exist %PREFIX%\\Menu\\powershell.ico exit 1

about:
  home: https://github.com/Semi-ATE/maxiconda-shortcuts
  summary: Shortcuts for the maxiconda installer
  license: BSD-3-Clause
  license_file: ../LICENSE

extra:
  recipe-maintainers:
    - nerohmot
