name: CD

on:
  release:
    types: [created]

jobs:
  make-release:
    runs-on: linux-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2

    - name: tag to version
      shell: bash -le {0}
      run: |
        cd recipe
        echo "{% set version = "${GITHUB_REF#refs/*/}" %}" > meta.yaml.versioned
        tail -n +2 meta.yaml >> meta.yaml.versioned
        cat meta.yaml.versioned
        mv -f meta.yaml.versioned meta.yaml
        cd ..

    - name: Publish Conda
      uses: fcakyon/conda-publish-action@v1.3
      with:
        subdir: 'recipe'
        anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
        platforms: 'win'
