name: CD

on:
  push:
    branches:
      - "*"

  pull_request:
    branches:
      - "*"

jobs:
  build-package:
    runs-on: windows-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
