name: CI

on:
  push:
    branches:
      - "*"

jobs:
  build-package:
    runs-on: windows-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2

    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: latest
        activate-environment: maxiconda-shortcuts
        environment-file: environment.yml
        channel-priority: strict

    - name: show environments
      shell: bash -l {0}
      run: |
        conda env list
        conda list

    - name: Create Conda Package 
      env:
        OUTPUT_FOLDER: D:/a/maxiconda-shortcuts/maxiconda-shortcuts
      shell: bash -l {0}
      run: |
        export MAXICONDA_SHORTCUTS_VERSION=${GITHUB_REF##*/}
        conda build recipe --output-folder $OUTPUT_FOLDER
        
