name: CI

on:
  push:
    branches:
      - "*"

  pull_request:
    branches:
      - "*"

jobs:
  build-package:
    runs-on: windows-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2

    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest" 
        python-version: '3.8'
        channel-priority: "strict"
        channels: "conda-forge"  
        mamba-version: "*"
        show-channel-urls: true 

    - name: show environments
      run: conda env list

    - name: Install conda-build & conda-verify
      run: mamba install -n test conda-build conda-verify -y

    - name: Create Conda Package
      run: |
        conda env list
        conda build ./recipe

#    - name: Upload Conda Package
#      run: blablabla
             
#    - name: Upload release assets
#      uses: alexellis/upload-assets@0.2.3
#      env:
#        GITHUB_TOKEN: ${{ github.token }}
#      with:
#        asset_paths: '["dist/Semi-ATE-*.tar.gz"]'      

#    - name: Publish Conda
#      uses: fcakyon/conda-publish-action@v1.3
#      with:
#        subdir: 'recipe'
#        anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
#        platforms: 'win'
