name: CI

on:
  push:
    branches:
      - "*"

  pull_request:
    branches:
      - "*"

jobs:
  build-package:
    runs-on: windows-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2

    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: latest
        activate-environment: maxiconda-shortcuts
        environment-file: environment.yml
        channel-priority: strict

    - name: show environments
      shell: bash -l {0}
      run: |
        conda env list
        conda list

    - name: Create Conda Package and upload
      env:
        CONDA_UPLOAD_TOKEN: ${{ secrets.CONDA_UPLOAD_TOKEN }}
        MAXICONDA_SHORTCUTS_VERSION: "0.0.1"
        OUTPUT_FOLDER: D:\a\maxiconda-shortcuts\maxiconda-shortcuts
      shell: bash -l {0}
      run: |
        conda build recipe --output-folder $OUTPUT_FOLDER
        anaconda upload -t $CONDA_UPLOAD_TOKEN -u semi-ate $OUTPUT_FOLDER\win-64\maxiconda-shortcuts-$MAXICONDA_SHORTCUTS_VERSION-0.tar.bz2 --force
